# Site settings
baseurl = "https://jacsmith21.github.io/"
languageCode = "en-us"
title = "Portfolio"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Test"
    subtitle = "This is a hugo site test using a very nice theme!"
    author = "Jacob Smith"
    description = "Information, projects & links!"
    keywords = "Jacob, Smith, Jacob Smith, UNB, Fredericton, portfolio, GitHub, resume, projects, about"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "View the source"

    # Footer text
    footertext = '<a href="https://github.com/jacsmith21" target="_blank"><i class="fa fa-github fa-2x"></i></a><a href="https://linkedin.com" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter fa-2x"></i></a>'

    # add extra-css
    custom_css = ['https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css', '/css/main.css']